### ISSUE TITLE
authentication support

### ISSUE THREAD

**Issue by adrai** [ActiveState/cloud-foundry-client-js#4]
Any ETA for authentication support for node?

**Comment by philwhln** [comment]
Hi @adrai,

For reference https://github.com/ActiveState/cloud-foundry-client-js/blob/0fcf57fa5286a9d62badafeea9b574f52e254992/api.js#L185-L196
```javascript
        api.prototype.authorizeNodejs = function (res, done) {

            /**
             * 1. If acting on behalf of a user e.g. just passing through a user token then a 401 is an error that should bubble out to the user
             * 2. If acting as a resource server a 401 should trigger a refresh token attempt and failing that it should try to re-authenticate using client credentials
             *
             * Assume 1. for now until 2. is implemented. Users of this lib could override this function to patch in their desired behaviour.
             */
            if (done) {
                done(new Error(makeErrorMessageFromResponse(res)), res);
            }
        };
```

We would definitely like to expand the implementation of this client, but do not currently have a need for 2. ourselves, so implementing, real-world testing and supporting it wouldn't make sense for us to do right now. Although, we would definitely appreciate a pull request if you do decide to implement this yourself.

Thanks,
Phil
ActiveState

**Comment by adrai** [comment]
Ol, thanks.
