### ISSUE TITLE
How to run cloudfoundry-client-js

### ISSUE THREAD

**Issue by jiangytcn** [ActiveState/cloud-foundry-client-js#5]
Hi
I  want to know whether the application is just a library i can use for my own nodejs application or an application that can run against cloudfoundry?
If 2nd, i don't find any documents about how runing it.

Tks.

**Comment by tara-gibbs** [comment]
Hello

This is a library to help you connect to the Cloud Foundry API. You can use it in your own Node.js applications by following the instructions in the [Node.js Usage](https://github.com/hpcloud/cloud-foundry-client-js#nodejs-usage) section of the README.

Cheers!
